import javax.swing.ImageIcon;
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        hotels_RadioGroupButton = new javax.swing.ButtonGroup();
        rooms_RadioButtonGroup = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hotels = new javax.swing.JPanel();
        AlArab = new javax.swing.JRadioButton();
        Hilton = new javax.swing.JRadioButton();
        IceHotel = new javax.swing.JRadioButton();
        Details = new javax.swing.JPanel();
        Breakfast = new javax.swing.JCheckBox();
        Dinner = new javax.swing.JCheckBox();
        ExtraTrip = new javax.swing.JCheckBox();
        Rooms = new javax.swing.JPanel();
        Single = new javax.swing.JRadioButton();
        Double = new javax.swing.JRadioButton();
        Suite = new javax.swing.JRadioButton();
        ShowImage = new javax.swing.JButton();
        RoomImage = new javax.swing.JLabel();
        Report = new javax.swing.JPanel();
        hotel = new javax.swing.JLabel();
        room = new javax.swing.JLabel();
        details = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Hotels.setLayout(new java.awt.GridBagLayout());

        hotels_RadioGroupButton.add(AlArab);
        AlArab.setToolTipText("Al Arab");
        AlArab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BurjAlArabHotelBW.jpg"))); // NOI18N
        AlArab.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BurjAlArabHotel.jpg"))); // NOI18N
        AlArab.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BurjAlArabHotel.jpg"))); // NOI18N
        AlArab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AlArabItemStateChanged(evt);
            }
        });
        AlArab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlArabActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        Hotels.add(AlArab, gridBagConstraints);

        hotels_RadioGroupButton.add(Hilton);
        Hilton.setToolTipText("Hilton");
        Hilton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hiltonhotelBW.jpg"))); // NOI18N
        Hilton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hiltonhotel.jpg"))); // NOI18N
        Hilton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hiltonhotel.jpg"))); // NOI18N
        Hilton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                HiltonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Hotels.add(Hilton, gridBagConstraints);

        hotels_RadioGroupButton.add(IceHotel);
        IceHotel.setToolTipText("IceHotel");
        IceHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icehotelBW.jpg"))); // NOI18N
        IceHotel.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icehotel.jpg"))); // NOI18N
        IceHotel.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icehotel.jpg"))); // NOI18N
        IceHotel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IceHotelItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Hotels.add(IceHotel, gridBagConstraints);

        jScrollPane1.setViewportView(Hotels);

        jTabbedPane1.addTab("Hotels", jScrollPane1);

        Details.setLayout(new java.awt.GridBagLayout());

        Breakfast.setText("Breakfast");
        Breakfast.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BreakfastItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Details.add(Breakfast, gridBagConstraints);

        Dinner.setText("Dinner");
        Dinner.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DinnerItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Details.add(Dinner, gridBagConstraints);

        ExtraTrip.setText("ExtraTip");
        ExtraTrip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ExtraTripItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Details.add(ExtraTrip, gridBagConstraints);

        jTabbedPane1.addTab("Details", Details);

        Rooms.setPreferredSize(new java.awt.Dimension(150, 150));
        Rooms.setLayout(new java.awt.GridBagLayout());

        rooms_RadioButtonGroup.add(Single);
        Single.setText("Single");
        Single.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SingleItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Rooms.add(Single, gridBagConstraints);

        rooms_RadioButtonGroup.add(Double);
        Double.setText("Double");
        Double.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DoubleItemStateChanged(evt);
            }
        });
        Double.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoubleActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Rooms.add(Double, gridBagConstraints);

        rooms_RadioButtonGroup.add(Suite);
        Suite.setText("Suite");
        Suite.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SuiteItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Rooms.add(Suite, gridBagConstraints);

        ShowImage.setText("Show Icon");
        ShowImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowImageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Rooms.add(ShowImage, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Rooms.add(RoomImage, gridBagConstraints);

        jTabbedPane1.addTab("Rooms", Rooms);

        Report.setLayout(new java.awt.GridBagLayout());

        hotel.setText("Hotel   : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Report.add(hotel, gridBagConstraints);

        room.setText("Room  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Report.add(room, gridBagConstraints);

        details.setText("Details : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Report.add(details, gridBagConstraints);

        jTabbedPane1.addTab("Report", Report);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlArabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlArabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlArabActionPerformed

    private void DoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoubleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoubleActionPerformed
ImageIcon AlArabSingle = new ImageIcon(getClass().getClassLoader().getResource("Images/AlArabSingle.jpg"));
ImageIcon AlArabDouble = new ImageIcon(getClass().getClassLoader().getResource("Images/AlArabDouble.jpg"));
ImageIcon AlArabSuite = new ImageIcon(getClass().getClassLoader().getResource("Images/AlArabSuite.jpg"));
ImageIcon HiltonSingle = new ImageIcon(getClass().getClassLoader().getResource("Images/HiltonSingle.jpg"));
ImageIcon HiltonDouble = new ImageIcon(getClass().getClassLoader().getResource("Images/HiltonDouble.jpg"));
ImageIcon HiltonSuite = new ImageIcon(getClass().getClassLoader().getResource("Images/HiltonSuite.jpg"));
ImageIcon IceHotelSingle = new ImageIcon(getClass().getClassLoader().getResource("Images/IceHotelSingle.jpg"));
ImageIcon IceHotelDouble = new ImageIcon(getClass().getClassLoader().getResource("Images/IceHotelDouble.jpg"));
ImageIcon IceHotelSuite = new ImageIcon(getClass().getClassLoader().getResource("Images/IceHotelSuite.jpg"));
    private void ShowImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowImageActionPerformed
        if(AlArab.isSelected()){
            if(Single.isSelected()){
                RoomImage.setIcon(AlArabSingle);
            }else if(Double.isSelected()){
                RoomImage.setIcon(AlArabDouble);
            }else{
                RoomImage.setIcon(AlArabSuite);
            }
        }else if(Hilton.isSelected()){
            if(Single.isSelected()){
                RoomImage.setIcon(HiltonSingle);
            }else if(Double.isSelected()){
                RoomImage.setIcon(HiltonDouble);
            }else{
                RoomImage.setIcon(HiltonSuite);
            }
        }else{
            if(Single.isSelected()){
                RoomImage.setIcon(IceHotelSingle);
            }else if(Double.isSelected()){
                RoomImage.setIcon(IceHotelDouble);
            }else{
                RoomImage.setIcon(IceHotelSuite);
            }
        }
    }//GEN-LAST:event_ShowImageActionPerformed

    private void AlArabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AlArabItemStateChanged
        hotel.setText("Hotel : AlArab");
    }//GEN-LAST:event_AlArabItemStateChanged

    private void HiltonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_HiltonItemStateChanged
        hotel.setText("Hotel : Hilton");
    }//GEN-LAST:event_HiltonItemStateChanged

    private void IceHotelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IceHotelItemStateChanged
        hotel.setText("Hotel : IceHotel");
    }//GEN-LAST:event_IceHotelItemStateChanged

    private void BreakfastItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BreakfastItemStateChanged
        String temp = details.getText();
        details.setText(temp + " Breakfast ");
    }//GEN-LAST:event_BreakfastItemStateChanged

    private void DinnerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DinnerItemStateChanged
        String temp = details.getText();
        details.setText(temp + " Dinner ");
    }//GEN-LAST:event_DinnerItemStateChanged

    private void ExtraTripItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ExtraTripItemStateChanged
        String temp = details.getText();
        details.setText(temp + " Extra Trip ");
    }//GEN-LAST:event_ExtraTripItemStateChanged

    private void SingleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SingleItemStateChanged
        room.setText("Room : Single");        // TODO add your handling code here:
    }//GEN-LAST:event_SingleItemStateChanged

    private void DoubleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DoubleItemStateChanged
         room.setText("Room : Double");  
    }//GEN-LAST:event_DoubleItemStateChanged

    private void SuiteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SuiteItemStateChanged
         room.setText("Room : Suite");  
    }//GEN-LAST:event_SuiteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlArab;
    private javax.swing.JCheckBox Breakfast;
    private javax.swing.JPanel Details;
    private javax.swing.JCheckBox Dinner;
    private javax.swing.JRadioButton Double;
    private javax.swing.JCheckBox ExtraTrip;
    private javax.swing.JRadioButton Hilton;
    private javax.swing.JPanel Hotels;
    private javax.swing.JRadioButton IceHotel;
    private javax.swing.JPanel Report;
    private javax.swing.JLabel RoomImage;
    private javax.swing.JPanel Rooms;
    private javax.swing.JButton ShowImage;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Suite;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel details;
    private javax.swing.JLabel hotel;
    private javax.swing.ButtonGroup hotels_RadioGroupButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel room;
    private javax.swing.ButtonGroup rooms_RadioButtonGroup;
    // End of variables declaration//GEN-END:variables
}
