import java.io.*;
        
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        openD = new javax.swing.JDialog();
        openDtext = new javax.swing.JTextField();
        openDopen = new javax.swing.JButton();
        openDcancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        saveD = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        saveDcancel = new javax.swing.JButton();
        saveDtext = new javax.swing.JTextField();
        saveDsave = new javax.swing.JButton();
        aboutD = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        println = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        SaveAs = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        Copy = new javax.swing.JMenuItem();
        Paste = new javax.swing.JMenuItem();
        Cut = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        About = new javax.swing.JMenuItem();

        openD.setTitle("open");

        openDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDtextActionPerformed(evt);
            }
        });

        openDopen.setText("Cancel");

        openDcancel.setText("Open");
        openDcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDcancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter the files route");

        javax.swing.GroupLayout openDLayout = new javax.swing.GroupLayout(openD.getContentPane());
        openD.getContentPane().setLayout(openDLayout);
        openDLayout.setHorizontalGroup(
            openDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openDLayout.createSequentialGroup()
                .addGroup(openDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openDLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(openDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(openDLayout.createSequentialGroup()
                                .addComponent(openDcancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(openDopen))
                            .addComponent(openDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(openDLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        openDLayout.setVerticalGroup(
            openDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(openDLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(openDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(openDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(openDLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(openDcancel))
                    .addGroup(openDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(openDopen)))
                .addGap(55, 55, 55))
        );

        saveD.setTitle("saveAs");

        jLabel2.setText("Enter the save route and the name of the file");

        saveDcancel.setText("Cancel");
        saveDcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDcancelActionPerformed(evt);
            }
        });

        saveDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDtextActionPerformed(evt);
            }
        });

        saveDsave.setText("Save");
        saveDsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDsaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveDLayout = new javax.swing.GroupLayout(saveD.getContentPane());
        saveD.getContentPane().setLayout(saveDLayout);
        saveDLayout.setHorizontalGroup(
            saveDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveDLayout.createSequentialGroup()
                .addContainerGap(95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(saveDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(saveDLayout.createSequentialGroup()
                        .addComponent(saveDsave)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saveDLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(saveDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveDtext, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(saveDcancel)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(101, 101, 101))))
        );
        saveDLayout.setVerticalGroup(
            saveDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveDLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(saveDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(saveDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDsave)
                    .addComponent(saveDcancel))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        aboutD.setTitle("About");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("This is A test For the Lab 8.\n\n\n\n\n\n\nV0.1\nLast Modified : 11/19/18");
        jScrollPane2.setViewportView(jTextArea1);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\index.jpg")); // NOI18N

        javax.swing.GroupLayout aboutDLayout = new javax.swing.GroupLayout(aboutD.getContentPane());
        aboutD.getContentPane().setLayout(aboutDLayout);
        aboutDLayout.setHorizontalGroup(
            aboutDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        aboutDLayout.setVerticalGroup(
            aboutDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutDLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Editor");

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        File.setText("File");

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Open.setMnemonic('O');
        Open.setText("Open");
        Open.setToolTipText("Open a text file");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);

        Close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Close.setMnemonic('E');
        Close.setText("Close");
        Close.setToolTipText("Close the file");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        File.add(Close);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setMnemonic('S');
        Save.setText("Save");
        Save.setToolTipText("Save a text file");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        File.add(Save);

        SaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        SaveAs.setMnemonic('A');
        SaveAs.setText("SaveAs");
        SaveAs.setToolTipText("Save as a text file");
        SaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsActionPerformed(evt);
            }
        });
        File.add(SaveAs);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, 0));
        Exit.setMnemonic('P');
        Exit.setText("Exit");
        Exit.setToolTipText("Exit from the program");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        Menu.add(File);

        Edit.setText("Edit");

        Copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Copy.setMnemonic('C');
        Copy.setText("Copy");
        Copy.setToolTipText("Copy the selected text");
        Copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyActionPerformed(evt);
            }
        });
        Edit.add(Copy);

        Paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        Paste.setMnemonic('V');
        Paste.setText("Paste");
        Paste.setToolTipText("Paste a saved text");
        Paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasteActionPerformed(evt);
            }
        });
        Edit.add(Paste);

        Cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Cut.setMnemonic('X');
        Cut.setText("Cut");
        Cut.setToolTipText("Cut a selected text");
        Cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutActionPerformed(evt);
            }
        });
        Edit.add(Cut);

        Menu.add(Edit);

        Help.setText("Help");

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Help.add(About);

        Menu.add(Help);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(println)
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(println)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
openD.setVisible(true);
openD.setSize(300,180);
}//GEN-LAST:event_OpenActionPerformed

private void PasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasteActionPerformed
Text.paste();
}//GEN-LAST:event_PasteActionPerformed

private void saveDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDtextActionPerformed

}//GEN-LAST:event_saveDtextActionPerformed

private void openDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDtextActionPerformed
route = openDtext.getText();
    FileReader fr; 
    if(route.equals(""))
        println.setText("Error");
    else{
        try{
            fr = new FileReader(route);
            Text.read(fr, null);
            fr.close();
            println.setText("Done");
        }
        catch(IOException exc){
            println.setText(exc.getMessage());
        }
    }
    openD.setVisible(false);
}//GEN-LAST:event_openDtextActionPerformed

private void saveDsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDsaveActionPerformed
route = saveDsave.getText();
    FileWriter saver ;
    if(route.equals(""))
        saveDsave.setText("Error");
    else{
        try{
            saver = new FileWriter(route);
            Text.write(saver);
            saver.close();
            saveDsave.setVisible(false);
            setTitle(saveDsave.getText());
            println.setText("Done");
        }
        catch(IOException exc){
            println.setText("Wrong file name");
        }
        println.setText("file saved!");
    }
    saveD.setVisible(false);
}//GEN-LAST:event_saveDsaveActionPerformed
String route;
private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
    FileWriter saver;
    route = saveDtext.getText();
    if(route.equals(""))
        saveD.setVisible(true);
    else{
        try{
            saver = new FileWriter(route);
            Text.write(saver);
            saver.close();
            println.setText("File saved");
        }
        catch(IOException exc){
            println.setText(exc.getMessage());
        }
    }
}//GEN-LAST:event_SaveActionPerformed

private void openDcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDcancelActionPerformed
openD.setVisible(false);
}//GEN-LAST:event_openDcancelActionPerformed

private void saveDcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDcancelActionPerformed
saveD.setVisible(false);
}//GEN-LAST:event_saveDcancelActionPerformed

private void SaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsActionPerformed
saveD.setVisible(true);
saveD.setSize(300,180);
}//GEN-LAST:event_SaveAsActionPerformed

private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
 Text.setText("");
 route = "";
 setTitle("Simple text editor");
}//GEN-LAST:event_CloseActionPerformed

private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
System.exit(0);
}//GEN-LAST:event_ExitActionPerformed

private void CopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyActionPerformed
Text.copy();
}//GEN-LAST:event_CopyActionPerformed

private void CutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutActionPerformed
Text.cut();
}//GEN-LAST:event_CutActionPerformed

private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
aboutD.setVisible(true);
aboutD.setSize(345,305);
}//GEN-LAST:event_AboutActionPerformed

    
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenuItem Copy;
    private javax.swing.JMenuItem Cut;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Paste;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JTextArea Text;
    private javax.swing.JDialog aboutD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog openD;
    private javax.swing.JButton openDcancel;
    private javax.swing.JButton openDopen;
    private javax.swing.JTextField openDtext;
    private javax.swing.JLabel println;
    private javax.swing.JDialog saveD;
    private javax.swing.JButton saveDcancel;
    private javax.swing.JButton saveDsave;
    private javax.swing.JTextField saveDtext;
    // End of variables declaration//GEN-END:variables
}
